# Generated by Django 5.2.6 on 2025-10-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Учитель')], default='student', max_length=10),
        ),
    ]
