# Generated by Django 5.2.6 on 2025-10-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Advertisement',
        ),
    ]
